### ISSUE TITLE
Change syntax of tags to array

### ISSUE THREAD

**Issue by minodisk** [minodisk/qiitactl#6]
## Reasons
-  When we write a tag without version. Objective syntax requires `:`, but arrayish syntax doesn't require it.
- Arrayish syntax ensures the order of tags.
### Now:

``` yaml
tags:
  Go:
  Ruby:
  - 0.0.1
```
### Will:

``` yaml
tags:
- Go
- Ruby:
  - 0.0.1
```
